root: true
env:
  browser: true
  node: true

plugins:
  - vue
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier

parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  parser: '@typescript-eslint/parser'

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  vue/script-indent:
    - error
    - 2
    - baseIndent: 1
      switchCase: 1
  vue/html-indent:
    - error
    - 2
    - baseIndent: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - 'error'
    - 'always-multiline'  # See https://eslint.org/docs/rules/comma-dangle#options

overrides:
  - files:
      - '*.vue'
    rules:
      indent: off
