root: true
env:
  browser: true
  node: true

plugins:
  - vue

extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended

parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  parser: '@typescript-eslint/parser'

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - 'error'
    - 'always-multiline'  # See https://eslint.org/docs/rules/comma-dangle#options
